version: "3.9"
services:
  maria-db:
    build: "./maria-db"
    container_name: "maria-db"
    networks:
      - my_net
    volumes:
      - wp_db:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: ["mysqld"]
    restart: on-failure
  php-fpm:
    build: "./php-fpm"
    container_name: "php-fpm"
    networks:
      - my_net
    volumes:
      - wp_files:/var/www/html
    ports:
      - "9000:9000"
    command: ["php-fpm7.3", "--nodaemonize"]
    env_file:
      - .env
    depends_on:
      - maria-db
    restart: on-failure
  nginx:
    build: "./nginx"
    container_name: "nginx"
    networks:
      - my_net
    volumes:
      - wp_files:/var/www/html
    ports:
      - "443:443"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - php-fpm
    restart: on-failure
  redis:
    build: "./redis"
    container_name: "redis"
    networks:
      - my_net
    ports:
      - "6379:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]
    depends_on:
      - php-fpm
    restart: on-failure
  vsftp:
    build:
      context: "./vsftp"
      args:
        - FTP_USERNAME=${FTP_USERNAME}
        - FTP_PASS=${FTP_PASS}
        - PUBLIC_HOST=${PUBLIC_HOST}
    container_name: "vsftp"
    networks:
      - my_net
    volumes:
      - wp_files:/var/www/html
    ports:
      - "4242:21"
      - "10100-10102:10100-10102"
    command: ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]
    env_file:
      - .env
    restart: on-failure

networks:
  my_net:
    driver : bridge
volumes:
  wp_db:
  wp_files:
