version: "3.9"
services:
  maria-db:
    build: "./maria-db"
    container_name: "maria-db"
    networks:
      - my_net
    volumes:
      - wp_db:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: ["mysqld"]
    restart: on-failure
  php-fpm:
    build: "./php-fpm"
    container_name: "php-fpm"
    networks:
      - my_net
    volumes:
      - wp_files:/var/www/html
    ports:
      - "9000:9000"
    command: ["php-fpm7.3", "--nodaemonize"]
    env_file:
      - .env
    depends_on:
      - maria-db
    restart: on-failure
  nginx:
    build: "./nginx"
    container_name: "nginx"
    networks:
      - my_net
    volumes:
      - wp_files:/var/www/html
      - adminer_files:/var/www/adminer
    ports:
      - "443:443"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - php-fpm
    restart: on-failure
  redis:
    build: "./redis"
    container_name: "redis"
    networks:
      - my_net
    ports:
      - "6379:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]
    depends_on:
      - php-fpm
    restart: on-failure
  vsftp:
    build:
      context: "./vsftp"
      args:
        - FTP_USERNAME=${FTP_USERNAME}
        - FTP_PASS=${FTP_PASS}
        - PUBLIC_HOST=${PUBLIC_HOST}
    container_name: "vsftp"
    networks:
      - my_net
    volumes:
      - wp_files:/var/www/html
    ports:
      - "4242:21"
      - "10100-10102:10100-10102"
    command: ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]
    env_file:
      - .env
    restart: on-failure
  php-fpm-adminer:
    build: "./php-fpm-adminer"
    container_name: "php-fpm-adminer"
    networks:
      - my_net
    volumes:
      - adminer_files:/var/www/adminer
    ports:
      - "9001:9001"
    command: ["php-fpm7.3", "--nodaemonize"]
    env_file:
      - .env
    restart: on-failure
  node_exporter:
    build: "./node_exporter"
    container_name: "node_exporter"
    networks:
      - my_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    command: ["prometheus-node-exporter", "--path.procfs=/host/proc", "--path.rootfs=/rootfs", "--path.sysfs=/host/sys", '--collector.filesystem.ignored-mount-points=^/\(sys\|proc\|dev\|host\|run\|etc\)', "--log.level=fatal"]
    env_file:
      - .env
    restart: on-failure
  prometheus:
    build: "./prometheus"
    container_name: "prometheus"
    networks:
      - my_net
    volumes:
      - prometheus_db:/prometheus
    ports:
      - "9090:9090"
    command: ["prometheus", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--log.level=error"]
    env_file:
      - .env
    restart: on-failure
  grafana:
    build: "./grafana"
    container_name: "grafana"
    networks:
      - my_net
    ports:
      - "3000:3000"
    command: [ "grafana-server", "--config=/etc/grafana/grafana.ini", "--pidfile=/var/run/grafana/grafana-server.pid", "--homepath=/usr/share/grafana" ]
    env_file:
      - .env
    restart: on-failure

networks:
  my_net:
    driver : bridge
volumes:
  wp_db:
  wp_files:
  adminer_files:
  prometheus_db:
