FROM centos:7

#ENTRYPOINT /bin/bash -c "i=10; while true; do echo On est toujours la \$i; sleep 5; ((i++)); done"
#ENTRYPOINT ["/bin/bash", "-c", "echo Hello World"]
ENTRYPOINT ['/bin/bash', '-c', 'i=10; while true; do echo On est toujours la \$i; sleep 5; ((i++)); done']
