.nh
.TH "DOCKER" "1" "Aug 2022" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-context-export - Export a context to a tar or kubeconfig file


.SH SYNOPSIS
.PP
\fBdocker context export [OPTIONS] CONTEXT [FILE|-]\fP


.SH DESCRIPTION
.PP
Export a context to a tar or kubeconfig file


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for export

.PP
\fB--kubeconfig\fP[=false]
	Export as a kubeconfig file


.SH SEE ALSO
.PP
\fBdocker-context(1)\fP
